#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrinterMonitoring.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_ALICE")]
	public partial class DtClassAppsDataContextDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertMenu_Aplikasi(Menu_Aplikasi instance);
    partial void UpdateMenu_Aplikasi(Menu_Aplikasi instance);
    partial void DeleteMenu_Aplikasi(Menu_Aplikasi instance);
    partial void InsertMenu_GP(Menu_GP instance);
    partial void UpdateMenu_GP(Menu_GP instance);
    partial void DeleteMenu_GP(Menu_GP instance);
    partial void InsertTBL_KARY_L(TBL_KARY_L instance);
    partial void UpdateTBL_KARY_L(TBL_KARY_L instance);
    partial void DeleteTBL_KARY_L(TBL_KARY_L instance);
    partial void InsertTBL_Profile(TBL_Profile instance);
    partial void UpdateTBL_Profile(TBL_Profile instance);
    partial void DeleteTBL_Profile(TBL_Profile instance);
    partial void InsertTBL_USER(TBL_USER instance);
    partial void UpdateTBL_USER(TBL_USER instance);
    partial void DeleteTBL_USER(TBL_USER instance);
    partial void InsertTBL_R_DASHBOARD_URL(TBL_R_DASHBOARD_URL instance);
    partial void UpdateTBL_R_DASHBOARD_URL(TBL_R_DASHBOARD_URL instance);
    partial void DeleteTBL_R_DASHBOARD_URL(TBL_R_DASHBOARD_URL instance);
    #endregion
		
		public DtClassAppsDataContextDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DB_ALICEConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DtClassAppsDataContextDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DtClassAppsDataContextDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DtClassAppsDataContextDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DtClassAppsDataContextDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Menu_Aplikasi> Menu_Aplikasis
		{
			get
			{
				return this.GetTable<Menu_Aplikasi>();
			}
		}
		
		public System.Data.Linq.Table<Menu_GP> Menu_GPs
		{
			get
			{
				return this.GetTable<Menu_GP>();
			}
		}
		
		public System.Data.Linq.Table<TBL_KARY_L> TBL_KARY_Ls
		{
			get
			{
				return this.GetTable<TBL_KARY_L>();
			}
		}
		
		public System.Data.Linq.Table<TBL_Profile> TBL_Profiles
		{
			get
			{
				return this.GetTable<TBL_Profile>();
			}
		}
		
		public System.Data.Linq.Table<TBL_USER> TBL_USERs
		{
			get
			{
				return this.GetTable<TBL_USER>();
			}
		}
		
		public System.Data.Linq.Table<TBL_R_DASHBOARD_URL> TBL_R_DASHBOARD_URLs
		{
			get
			{
				return this.GetTable<TBL_R_DASHBOARD_URL>();
			}
		}
		
		public System.Data.Linq.Table<Menu> Menus
		{
			get
			{
				return this.GetTable<Menu>();
			}
		}
		
		public System.Data.Linq.Table<vw_DEPT> vw_DEPTs
		{
			get
			{
				return this.GetTable<vw_DEPT>();
			}
		}
		
		public System.Data.Linq.Table<VW_DWH_DISTRIK> VW_DWH_DISTRIKs
		{
			get
			{
				return this.GetTable<VW_DWH_DISTRIK>();
			}
		}
		
		public System.Data.Linq.Table<vw_employee> vw_employees
		{
			get
			{
				return this.GetTable<vw_employee>();
			}
		}
		
		public System.Data.Linq.Table<vw_menuCrossGPID> vw_menuCrossGPIDs
		{
			get
			{
				return this.GetTable<vw_menuCrossGPID>();
			}
		}
		
		public System.Data.Linq.Table<vw_gpId> vw_gpIds
		{
			get
			{
				return this.GetTable<vw_gpId>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Apps.cusp_getMenuPermissions")]
		public ISingleResult<cusp_getMenuPermissionsResult> cusp_getMenuPermissions([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GP_ID", DbType="Int")] System.Nullable<int> gP_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Link", DbType="VarChar(100)")] string link)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gP_ID, link);
			return ((ISingleResult<cusp_getMenuPermissionsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Apps.cusp_SetMenuGP")]
		public int cusp_SetMenuGP([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> sPrimer, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> sGP_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> sIsCheck, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> sIsAdd, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> sIsDelete, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> sIsEdit, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> sIsRead)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sPrimer, sGP_ID, sIsCheck, sIsAdd, sIsDelete, sIsEdit, sIsRead);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Apps.Menu_Aplikasi")]
	public partial class Menu_Aplikasi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Primer;
		
		private int _Id;
		
		private string _Menu;
		
		private System.Nullable<int> _Menu_link;
		
		private string _Link;
		
		private System.Nullable<int> _Urutan;
		
		private string _Deskripsi;
		
		private string _style_class;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPrimerChanging(long value);
    partial void OnPrimerChanged();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnMenuChanging(string value);
    partial void OnMenuChanged();
    partial void OnMenu_linkChanging(System.Nullable<int> value);
    partial void OnMenu_linkChanged();
    partial void OnLinkChanging(string value);
    partial void OnLinkChanged();
    partial void OnUrutanChanging(System.Nullable<int> value);
    partial void OnUrutanChanged();
    partial void OnDeskripsiChanging(string value);
    partial void OnDeskripsiChanged();
    partial void Onstyle_classChanging(string value);
    partial void Onstyle_classChanged();
    #endregion
		
		public Menu_Aplikasi()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Primer", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long Primer
		{
			get
			{
				return this._Primer;
			}
			set
			{
				if ((this._Primer != value))
				{
					this.OnPrimerChanging(value);
					this.SendPropertyChanging();
					this._Primer = value;
					this.SendPropertyChanged("Primer");
					this.OnPrimerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Menu", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Menu
		{
			get
			{
				return this._Menu;
			}
			set
			{
				if ((this._Menu != value))
				{
					this.OnMenuChanging(value);
					this.SendPropertyChanging();
					this._Menu = value;
					this.SendPropertyChanged("Menu");
					this.OnMenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Menu_link", DbType="Int")]
		public System.Nullable<int> Menu_link
		{
			get
			{
				return this._Menu_link;
			}
			set
			{
				if ((this._Menu_link != value))
				{
					this.OnMenu_linkChanging(value);
					this.SendPropertyChanging();
					this._Menu_link = value;
					this.SendPropertyChanged("Menu_link");
					this.OnMenu_linkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Link", DbType="NVarChar(1000)")]
		public string Link
		{
			get
			{
				return this._Link;
			}
			set
			{
				if ((this._Link != value))
				{
					this.OnLinkChanging(value);
					this.SendPropertyChanging();
					this._Link = value;
					this.SendPropertyChanged("Link");
					this.OnLinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Urutan", DbType="Int")]
		public System.Nullable<int> Urutan
		{
			get
			{
				return this._Urutan;
			}
			set
			{
				if ((this._Urutan != value))
				{
					this.OnUrutanChanging(value);
					this.SendPropertyChanging();
					this._Urutan = value;
					this.SendPropertyChanged("Urutan");
					this.OnUrutanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deskripsi", DbType="VarChar(250)")]
		public string Deskripsi
		{
			get
			{
				return this._Deskripsi;
			}
			set
			{
				if ((this._Deskripsi != value))
				{
					this.OnDeskripsiChanging(value);
					this.SendPropertyChanging();
					this._Deskripsi = value;
					this.SendPropertyChanged("Deskripsi");
					this.OnDeskripsiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_style_class", DbType="VarChar(50)")]
		public string style_class
		{
			get
			{
				return this._style_class;
			}
			set
			{
				if ((this._style_class != value))
				{
					this.Onstyle_classChanging(value);
					this.SendPropertyChanging();
					this._style_class = value;
					this.SendPropertyChanged("style_class");
					this.Onstyle_classChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Apps.Menu_GP")]
	public partial class Menu_GP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Primer;
		
		private long _GP_ID;
		
		private string _Permission;
		
		private System.Nullable<bool> _A;
		
		private System.Nullable<bool> _D;
		
		private System.Nullable<bool> _E;
		
		private System.Nullable<bool> _R;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPrimerChanging(long value);
    partial void OnPrimerChanged();
    partial void OnGP_IDChanging(long value);
    partial void OnGP_IDChanged();
    partial void OnPermissionChanging(string value);
    partial void OnPermissionChanged();
    partial void OnAChanging(System.Nullable<bool> value);
    partial void OnAChanged();
    partial void OnDChanging(System.Nullable<bool> value);
    partial void OnDChanged();
    partial void OnEChanging(System.Nullable<bool> value);
    partial void OnEChanged();
    partial void OnRChanging(System.Nullable<bool> value);
    partial void OnRChanged();
    #endregion
		
		public Menu_GP()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Primer", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long Primer
		{
			get
			{
				return this._Primer;
			}
			set
			{
				if ((this._Primer != value))
				{
					this.OnPrimerChanging(value);
					this.SendPropertyChanging();
					this._Primer = value;
					this.SendPropertyChanged("Primer");
					this.OnPrimerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GP_ID", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long GP_ID
		{
			get
			{
				return this._GP_ID;
			}
			set
			{
				if ((this._GP_ID != value))
				{
					this.OnGP_IDChanging(value);
					this.SendPropertyChanging();
					this._GP_ID = value;
					this.SendPropertyChanged("GP_ID");
					this.OnGP_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Permission", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Permission
		{
			get
			{
				return this._Permission;
			}
			set
			{
				if ((this._Permission != value))
				{
					this.OnPermissionChanging(value);
					this.SendPropertyChanging();
					this._Permission = value;
					this.SendPropertyChanged("Permission");
					this.OnPermissionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A", DbType="Bit")]
		public System.Nullable<bool> A
		{
			get
			{
				return this._A;
			}
			set
			{
				if ((this._A != value))
				{
					this.OnAChanging(value);
					this.SendPropertyChanging();
					this._A = value;
					this.SendPropertyChanged("A");
					this.OnAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D", DbType="Bit")]
		public System.Nullable<bool> D
		{
			get
			{
				return this._D;
			}
			set
			{
				if ((this._D != value))
				{
					this.OnDChanging(value);
					this.SendPropertyChanging();
					this._D = value;
					this.SendPropertyChanged("D");
					this.OnDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E", DbType="Bit")]
		public System.Nullable<bool> E
		{
			get
			{
				return this._E;
			}
			set
			{
				if ((this._E != value))
				{
					this.OnEChanging(value);
					this.SendPropertyChanging();
					this._E = value;
					this.SendPropertyChanged("E");
					this.OnEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R", DbType="Bit")]
		public System.Nullable<bool> R
		{
			get
			{
				return this._R;
			}
			set
			{
				if ((this._R != value))
				{
					this.OnRChanging(value);
					this.SendPropertyChanging();
					this._R = value;
					this.SendPropertyChanged("R");
					this.OnRChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Apps.TBL_KARY_LS")]
	public partial class TBL_KARY_L : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _PID_LS;
		
		private string _NRP;
		
		private string _NAME;
		
		private string _DSTRCT_CODE;
		
		private string _POS_TITLE;
		
		private string _DEPT_CODE;
		
		private string _Address_LotusNotes;
		
		private string _CREATED_BY;
		
		private System.Nullable<System.DateTime> _CREATED_DATE;
		
		private string _LAST_MODIFIED_BY;
		
		private System.Nullable<System.DateTime> _LAST_MODIFIED_DATE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPID_LSChanging(string value);
    partial void OnPID_LSChanged();
    partial void OnNRPChanging(string value);
    partial void OnNRPChanged();
    partial void OnNAMEChanging(string value);
    partial void OnNAMEChanged();
    partial void OnDSTRCT_CODEChanging(string value);
    partial void OnDSTRCT_CODEChanged();
    partial void OnPOS_TITLEChanging(string value);
    partial void OnPOS_TITLEChanged();
    partial void OnDEPT_CODEChanging(string value);
    partial void OnDEPT_CODEChanged();
    partial void OnAddress_LotusNotesChanging(string value);
    partial void OnAddress_LotusNotesChanged();
    partial void OnCREATED_BYChanging(string value);
    partial void OnCREATED_BYChanged();
    partial void OnCREATED_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnCREATED_DATEChanged();
    partial void OnLAST_MODIFIED_BYChanging(string value);
    partial void OnLAST_MODIFIED_BYChanged();
    partial void OnLAST_MODIFIED_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnLAST_MODIFIED_DATEChanged();
    #endregion
		
		public TBL_KARY_L()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PID_LS", DbType="VarChar(250) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string PID_LS
		{
			get
			{
				return this._PID_LS;
			}
			set
			{
				if ((this._PID_LS != value))
				{
					this.OnPID_LSChanging(value);
					this.SendPropertyChanging();
					this._PID_LS = value;
					this.SendPropertyChanged("PID_LS");
					this.OnPID_LSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NRP", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NRP
		{
			get
			{
				return this._NRP;
			}
			set
			{
				if ((this._NRP != value))
				{
					this.OnNRPChanging(value);
					this.SendPropertyChanging();
					this._NRP = value;
					this.SendPropertyChanged("NRP");
					this.OnNRPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this.OnNAMEChanging(value);
					this.SendPropertyChanging();
					this._NAME = value;
					this.SendPropertyChanged("NAME");
					this.OnNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSTRCT_CODE", DbType="VarChar(4) NOT NULL", CanBeNull=false)]
		public string DSTRCT_CODE
		{
			get
			{
				return this._DSTRCT_CODE;
			}
			set
			{
				if ((this._DSTRCT_CODE != value))
				{
					this.OnDSTRCT_CODEChanging(value);
					this.SendPropertyChanging();
					this._DSTRCT_CODE = value;
					this.SendPropertyChanged("DSTRCT_CODE");
					this.OnDSTRCT_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POS_TITLE", DbType="VarChar(250)")]
		public string POS_TITLE
		{
			get
			{
				return this._POS_TITLE;
			}
			set
			{
				if ((this._POS_TITLE != value))
				{
					this.OnPOS_TITLEChanging(value);
					this.SendPropertyChanging();
					this._POS_TITLE = value;
					this.SendPropertyChanged("POS_TITLE");
					this.OnPOS_TITLEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_CODE", DbType="VarChar(250)")]
		public string DEPT_CODE
		{
			get
			{
				return this._DEPT_CODE;
			}
			set
			{
				if ((this._DEPT_CODE != value))
				{
					this.OnDEPT_CODEChanging(value);
					this.SendPropertyChanging();
					this._DEPT_CODE = value;
					this.SendPropertyChanged("DEPT_CODE");
					this.OnDEPT_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address_LotusNotes", DbType="VarChar(255)")]
		public string Address_LotusNotes
		{
			get
			{
				return this._Address_LotusNotes;
			}
			set
			{
				if ((this._Address_LotusNotes != value))
				{
					this.OnAddress_LotusNotesChanging(value);
					this.SendPropertyChanging();
					this._Address_LotusNotes = value;
					this.SendPropertyChanged("Address_LotusNotes");
					this.OnAddress_LotusNotesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATED_BY", DbType="VarChar(10)")]
		public string CREATED_BY
		{
			get
			{
				return this._CREATED_BY;
			}
			set
			{
				if ((this._CREATED_BY != value))
				{
					this.OnCREATED_BYChanging(value);
					this.SendPropertyChanging();
					this._CREATED_BY = value;
					this.SendPropertyChanged("CREATED_BY");
					this.OnCREATED_BYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATED_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATED_DATE
		{
			get
			{
				return this._CREATED_DATE;
			}
			set
			{
				if ((this._CREATED_DATE != value))
				{
					this.OnCREATED_DATEChanging(value);
					this.SendPropertyChanging();
					this._CREATED_DATE = value;
					this.SendPropertyChanged("CREATED_DATE");
					this.OnCREATED_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_MODIFIED_BY", DbType="VarChar(10)")]
		public string LAST_MODIFIED_BY
		{
			get
			{
				return this._LAST_MODIFIED_BY;
			}
			set
			{
				if ((this._LAST_MODIFIED_BY != value))
				{
					this.OnLAST_MODIFIED_BYChanging(value);
					this.SendPropertyChanging();
					this._LAST_MODIFIED_BY = value;
					this.SendPropertyChanged("LAST_MODIFIED_BY");
					this.OnLAST_MODIFIED_BYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_MODIFIED_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> LAST_MODIFIED_DATE
		{
			get
			{
				return this._LAST_MODIFIED_DATE;
			}
			set
			{
				if ((this._LAST_MODIFIED_DATE != value))
				{
					this.OnLAST_MODIFIED_DATEChanging(value);
					this.SendPropertyChanging();
					this._LAST_MODIFIED_DATE = value;
					this.SendPropertyChanged("LAST_MODIFIED_DATE");
					this.OnLAST_MODIFIED_DATEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Apps.TBL_Profile")]
	public partial class TBL_Profile : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _GP_ID;
		
		private string _Deskripsi;
		
		private System.Nullable<bool> _isAllSIte;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGP_IDChanging(long value);
    partial void OnGP_IDChanged();
    partial void OnDeskripsiChanging(string value);
    partial void OnDeskripsiChanged();
    partial void OnisAllSIteChanging(System.Nullable<bool> value);
    partial void OnisAllSIteChanged();
    #endregion
		
		public TBL_Profile()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GP_ID", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long GP_ID
		{
			get
			{
				return this._GP_ID;
			}
			set
			{
				if ((this._GP_ID != value))
				{
					this.OnGP_IDChanging(value);
					this.SendPropertyChanging();
					this._GP_ID = value;
					this.SendPropertyChanged("GP_ID");
					this.OnGP_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deskripsi", DbType="VarChar(50)")]
		public string Deskripsi
		{
			get
			{
				return this._Deskripsi;
			}
			set
			{
				if ((this._Deskripsi != value))
				{
					this.OnDeskripsiChanging(value);
					this.SendPropertyChanging();
					this._Deskripsi = value;
					this.SendPropertyChanged("Deskripsi");
					this.OnDeskripsiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isAllSIte", DbType="Bit")]
		public System.Nullable<bool> isAllSIte
		{
			get
			{
				return this._isAllSIte;
			}
			set
			{
				if ((this._isAllSIte != value))
				{
					this.OnisAllSIteChanging(value);
					this.SendPropertyChanging();
					this._isAllSIte = value;
					this.SendPropertyChanged("isAllSIte");
					this.OnisAllSIteChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Apps.TBL_USER")]
	public partial class TBL_USER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _NRP;
		
		private long _GP;
		
		private string _DISTRIK;
		
		private System.Nullable<int> _Autorize;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNRPChanging(string value);
    partial void OnNRPChanged();
    partial void OnGPChanging(long value);
    partial void OnGPChanged();
    partial void OnDISTRIKChanging(string value);
    partial void OnDISTRIKChanged();
    partial void OnAutorizeChanging(System.Nullable<int> value);
    partial void OnAutorizeChanged();
    #endregion
		
		public TBL_USER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NRP", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string NRP
		{
			get
			{
				return this._NRP;
			}
			set
			{
				if ((this._NRP != value))
				{
					this.OnNRPChanging(value);
					this.SendPropertyChanging();
					this._NRP = value;
					this.SendPropertyChanged("NRP");
					this.OnNRPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GP", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long GP
		{
			get
			{
				return this._GP;
			}
			set
			{
				if ((this._GP != value))
				{
					this.OnGPChanging(value);
					this.SendPropertyChanging();
					this._GP = value;
					this.SendPropertyChanged("GP");
					this.OnGPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISTRIK", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string DISTRIK
		{
			get
			{
				return this._DISTRIK;
			}
			set
			{
				if ((this._DISTRIK != value))
				{
					this.OnDISTRIKChanging(value);
					this.SendPropertyChanging();
					this._DISTRIK = value;
					this.SendPropertyChanged("DISTRIK");
					this.OnDISTRIKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Autorize", DbType="Int")]
		public System.Nullable<int> Autorize
		{
			get
			{
				return this._Autorize;
			}
			set
			{
				if ((this._Autorize != value))
				{
					this.OnAutorizeChanging(value);
					this.SendPropertyChanging();
					this._Autorize = value;
					this.SendPropertyChanged("Autorize");
					this.OnAutorizeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_R_DASHBOARD_URL")]
	public partial class TBL_R_DASHBOARD_URL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _pid_dashboard;
		
		private string _PROFILE_DASHBOARD;
		
		private string _DSTRCT_CODE;
		
		private string _LINK_DASHBOARD;
		
		private string _NAMA_DASHBOARD;
		
		private string _UPDATE_BY;
		
		private System.Nullable<System.DateTime> _UPDATE_DATE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpid_dashboardChanging(string value);
    partial void Onpid_dashboardChanged();
    partial void OnPROFILE_DASHBOARDChanging(string value);
    partial void OnPROFILE_DASHBOARDChanged();
    partial void OnDSTRCT_CODEChanging(string value);
    partial void OnDSTRCT_CODEChanged();
    partial void OnLINK_DASHBOARDChanging(string value);
    partial void OnLINK_DASHBOARDChanged();
    partial void OnNAMA_DASHBOARDChanging(string value);
    partial void OnNAMA_DASHBOARDChanged();
    partial void OnUPDATE_BYChanging(string value);
    partial void OnUPDATE_BYChanged();
    partial void OnUPDATE_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnUPDATE_DATEChanged();
    #endregion
		
		public TBL_R_DASHBOARD_URL()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pid_dashboard", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string pid_dashboard
		{
			get
			{
				return this._pid_dashboard;
			}
			set
			{
				if ((this._pid_dashboard != value))
				{
					this.Onpid_dashboardChanging(value);
					this.SendPropertyChanging();
					this._pid_dashboard = value;
					this.SendPropertyChanged("pid_dashboard");
					this.Onpid_dashboardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROFILE_DASHBOARD", DbType="VarChar(50)")]
		public string PROFILE_DASHBOARD
		{
			get
			{
				return this._PROFILE_DASHBOARD;
			}
			set
			{
				if ((this._PROFILE_DASHBOARD != value))
				{
					this.OnPROFILE_DASHBOARDChanging(value);
					this.SendPropertyChanging();
					this._PROFILE_DASHBOARD = value;
					this.SendPropertyChanged("PROFILE_DASHBOARD");
					this.OnPROFILE_DASHBOARDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSTRCT_CODE", DbType="VarChar(10)")]
		public string DSTRCT_CODE
		{
			get
			{
				return this._DSTRCT_CODE;
			}
			set
			{
				if ((this._DSTRCT_CODE != value))
				{
					this.OnDSTRCT_CODEChanging(value);
					this.SendPropertyChanging();
					this._DSTRCT_CODE = value;
					this.SendPropertyChanged("DSTRCT_CODE");
					this.OnDSTRCT_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LINK_DASHBOARD", DbType="VarChar(MAX)")]
		public string LINK_DASHBOARD
		{
			get
			{
				return this._LINK_DASHBOARD;
			}
			set
			{
				if ((this._LINK_DASHBOARD != value))
				{
					this.OnLINK_DASHBOARDChanging(value);
					this.SendPropertyChanging();
					this._LINK_DASHBOARD = value;
					this.SendPropertyChanged("LINK_DASHBOARD");
					this.OnLINK_DASHBOARDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAMA_DASHBOARD", DbType="VarChar(MAX)")]
		public string NAMA_DASHBOARD
		{
			get
			{
				return this._NAMA_DASHBOARD;
			}
			set
			{
				if ((this._NAMA_DASHBOARD != value))
				{
					this.OnNAMA_DASHBOARDChanging(value);
					this.SendPropertyChanging();
					this._NAMA_DASHBOARD = value;
					this.SendPropertyChanged("NAMA_DASHBOARD");
					this.OnNAMA_DASHBOARDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATE_BY", DbType="VarChar(100)")]
		public string UPDATE_BY
		{
			get
			{
				return this._UPDATE_BY;
			}
			set
			{
				if ((this._UPDATE_BY != value))
				{
					this.OnUPDATE_BYChanging(value);
					this.SendPropertyChanging();
					this._UPDATE_BY = value;
					this.SendPropertyChanged("UPDATE_BY");
					this.OnUPDATE_BYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATE_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> UPDATE_DATE
		{
			get
			{
				return this._UPDATE_DATE;
			}
			set
			{
				if ((this._UPDATE_DATE != value))
				{
					this.OnUPDATE_DATEChanging(value);
					this.SendPropertyChanging();
					this._UPDATE_DATE = value;
					this.SendPropertyChanged("UPDATE_DATE");
					this.OnUPDATE_DATEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Apps.Menu")]
	public partial class Menu
	{
		
		private int _Id;
		
		private string _Menu1;
		
		private System.Nullable<int> _Menu_link;
		
		private string _Link;
		
		private System.Nullable<int> _Urutan;
		
		private long _GP_ID;
		
		private string _Deskripsi;
		
		private string _Permission;
		
		private System.Nullable<bool> _A;
		
		private System.Nullable<bool> _D;
		
		private System.Nullable<bool> _E;
		
		private System.Nullable<bool> _R;
		
		private string _style_class;
		
		public Menu()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Menu", Storage="_Menu1", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Menu1
		{
			get
			{
				return this._Menu1;
			}
			set
			{
				if ((this._Menu1 != value))
				{
					this._Menu1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Menu_link", DbType="Int")]
		public System.Nullable<int> Menu_link
		{
			get
			{
				return this._Menu_link;
			}
			set
			{
				if ((this._Menu_link != value))
				{
					this._Menu_link = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Link", DbType="NVarChar(1000)")]
		public string Link
		{
			get
			{
				return this._Link;
			}
			set
			{
				if ((this._Link != value))
				{
					this._Link = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Urutan", DbType="Int")]
		public System.Nullable<int> Urutan
		{
			get
			{
				return this._Urutan;
			}
			set
			{
				if ((this._Urutan != value))
				{
					this._Urutan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GP_ID", DbType="BigInt NOT NULL")]
		public long GP_ID
		{
			get
			{
				return this._GP_ID;
			}
			set
			{
				if ((this._GP_ID != value))
				{
					this._GP_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deskripsi", DbType="VarChar(250)")]
		public string Deskripsi
		{
			get
			{
				return this._Deskripsi;
			}
			set
			{
				if ((this._Deskripsi != value))
				{
					this._Deskripsi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Permission", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Permission
		{
			get
			{
				return this._Permission;
			}
			set
			{
				if ((this._Permission != value))
				{
					this._Permission = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A", DbType="Bit")]
		public System.Nullable<bool> A
		{
			get
			{
				return this._A;
			}
			set
			{
				if ((this._A != value))
				{
					this._A = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D", DbType="Bit")]
		public System.Nullable<bool> D
		{
			get
			{
				return this._D;
			}
			set
			{
				if ((this._D != value))
				{
					this._D = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E", DbType="Bit")]
		public System.Nullable<bool> E
		{
			get
			{
				return this._E;
			}
			set
			{
				if ((this._E != value))
				{
					this._E = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R", DbType="Bit")]
		public System.Nullable<bool> R
		{
			get
			{
				return this._R;
			}
			set
			{
				if ((this._R != value))
				{
					this._R = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_style_class", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string style_class
		{
			get
			{
				return this._style_class;
			}
			set
			{
				if ((this._style_class != value))
				{
					this._style_class = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Apps.vw_DEPT")]
	public partial class vw_DEPT
	{
		
		private string _DSTRCT_CODE;
		
		private string _DEPT_CODE;
		
		private string _DEPT_DESC;
		
		public vw_DEPT()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSTRCT_CODE", DbType="VarChar(4) NOT NULL", CanBeNull=false)]
		public string DSTRCT_CODE
		{
			get
			{
				return this._DSTRCT_CODE;
			}
			set
			{
				if ((this._DSTRCT_CODE != value))
				{
					this._DSTRCT_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_CODE", DbType="VarChar(4) NOT NULL", CanBeNull=false)]
		public string DEPT_CODE
		{
			get
			{
				return this._DEPT_CODE;
			}
			set
			{
				if ((this._DEPT_CODE != value))
				{
					this._DEPT_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_DESC", DbType="VarChar(50)")]
		public string DEPT_DESC
		{
			get
			{
				return this._DEPT_DESC;
			}
			set
			{
				if ((this._DEPT_DESC != value))
				{
					this._DEPT_DESC = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Apps.VW_DWH_DISTRIK")]
	public partial class VW_DWH_DISTRIK
	{
		
		private string _DSTRCT_CODE;
		
		private string _DSTRCT_NAME;
		
		public VW_DWH_DISTRIK()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSTRCT_CODE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string DSTRCT_CODE
		{
			get
			{
				return this._DSTRCT_CODE;
			}
			set
			{
				if ((this._DSTRCT_CODE != value))
				{
					this._DSTRCT_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSTRCT_NAME", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string DSTRCT_NAME
		{
			get
			{
				return this._DSTRCT_NAME;
			}
			set
			{
				if ((this._DSTRCT_NAME != value))
				{
					this._DSTRCT_NAME = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Apps.vw_employee")]
	public partial class vw_employee
	{
		
		private string _EMPLOYEE_ID;
		
		private string _FIRST_NAME;
		
		private string _SURNAME;
		
		private string _NAME;
		
		private string _POSITION_ID;
		
		private string _POS_TITLE;
		
		private string _CHANGE_REASON;
		
		private string _CHANGE_REASON_DESC;
		
		private string _DSTRCT_CODE;
		
		private string _WORK_LOC;
		
		private string _WORK_LOC_DESC;
		
		private string _EMP_STATUS;
		
		private string _EMP_STATUS_DESC;
		
		private string _GENDER_CODE;
		
		private string _GENDER_DESC;
		
		private string _EMP_TYPE;
		
		private string _EMP_TYPE_DESC;
		
		private string _STAFF_CATEG;
		
		private string _STAFF_CATEG_DESC;
		
		private string _BIRTH_DATE;
		
		private string _HIRE_DATE;
		
		private string _SERVICE_DATE;
		
		private string _TERMINATION_DATE;
		
		private string _STATUS_HIRE;
		
		private string _STATUS_HIRE_DESC;
		
		private string _POINT_OF_HIRE;
		
		private string _POINT_OF_HIRE_DESC;
		
		private string _ACCOUNT_DOMAIN;
		
		private string _NRP;
		
		private System.Nullable<int> _AGE;
		
		private string _BLOOD_TYPE;
		
		private string _RELIGION_DESC;
		
		private string _RES_ADDRESS_1;
		
		private string _RES_ADDRESS_2;
		
		private string _RES_ADDRESS_3;
		
		private string _RES_ZIPCODE;
		
		private string _SUPERIOR_ID;
		
		private string _POSITION_START_DATE;
		
		private string _GOLONGAN;
		
		private string _GOL_COMPTCY_LEVEL;
		
		private string _GOL_START_DATE;
		
		private string _HOME_PHONE_NO;
		
		private string _HOME_MOBILE_NO;
		
		private string _RANKS;
		
		private string _RANK_DESC;
		
		private string _RANK_START_DATE;
		
		private string _DEPT_CODE;
		
		private string _DEPT_DESC;
		
		private string _DEPT_CODE_DESC;
		
		private string _DIV_CODE;
		
		private string _DIV_DESC;
		
		private string _DIV_CODE_DESC;
		
		private string _Address_LotusNotes;
		
		private string _Email_Internet;
		
		private System.Nullable<int> _ACTIVE_STATUS;
		
		private string _GENDER;
		
		private string _NAME_INITCAP;
		
		private string _RELIGION;
		
		private System.Nullable<System.DateTime> _MODIFIED_DATE;
		
		private string _RANKS_DESC;
		
		private string _RANKS_START_DATE;
		
		private string _SECONDARY_POSITION_ID;
		
		private string _LAST_EDUCATION;
		
		private string _BIRTH_PLACE;
		
		private string _BIRTH_PLACE_DESC;
		
		private string _GROUP_GOLONGAN;
		
		private string _STATUS_EMP;
		
		public vw_employee()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMPLOYEE_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string EMPLOYEE_ID
		{
			get
			{
				return this._EMPLOYEE_ID;
			}
			set
			{
				if ((this._EMPLOYEE_ID != value))
				{
					this._EMPLOYEE_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIRST_NAME", DbType="VarChar(250)")]
		public string FIRST_NAME
		{
			get
			{
				return this._FIRST_NAME;
			}
			set
			{
				if ((this._FIRST_NAME != value))
				{
					this._FIRST_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SURNAME", DbType="VarChar(250)")]
		public string SURNAME
		{
			get
			{
				return this._SURNAME;
			}
			set
			{
				if ((this._SURNAME != value))
				{
					this._SURNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="VarChar(250)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSITION_ID", DbType="VarChar(10)")]
		public string POSITION_ID
		{
			get
			{
				return this._POSITION_ID;
			}
			set
			{
				if ((this._POSITION_ID != value))
				{
					this._POSITION_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POS_TITLE", DbType="VarChar(250)")]
		public string POS_TITLE
		{
			get
			{
				return this._POS_TITLE;
			}
			set
			{
				if ((this._POS_TITLE != value))
				{
					this._POS_TITLE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHANGE_REASON", DbType="VarChar(2)")]
		public string CHANGE_REASON
		{
			get
			{
				return this._CHANGE_REASON;
			}
			set
			{
				if ((this._CHANGE_REASON != value))
				{
					this._CHANGE_REASON = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHANGE_REASON_DESC", DbType="VarChar(50)")]
		public string CHANGE_REASON_DESC
		{
			get
			{
				return this._CHANGE_REASON_DESC;
			}
			set
			{
				if ((this._CHANGE_REASON_DESC != value))
				{
					this._CHANGE_REASON_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSTRCT_CODE", DbType="VarChar(50)")]
		public string DSTRCT_CODE
		{
			get
			{
				return this._DSTRCT_CODE;
			}
			set
			{
				if ((this._DSTRCT_CODE != value))
				{
					this._DSTRCT_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WORK_LOC", DbType="VarChar(5)")]
		public string WORK_LOC
		{
			get
			{
				return this._WORK_LOC;
			}
			set
			{
				if ((this._WORK_LOC != value))
				{
					this._WORK_LOC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WORK_LOC_DESC", DbType="VarChar(50)")]
		public string WORK_LOC_DESC
		{
			get
			{
				return this._WORK_LOC_DESC;
			}
			set
			{
				if ((this._WORK_LOC_DESC != value))
				{
					this._WORK_LOC_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_STATUS", DbType="VarChar(1)")]
		public string EMP_STATUS
		{
			get
			{
				return this._EMP_STATUS;
			}
			set
			{
				if ((this._EMP_STATUS != value))
				{
					this._EMP_STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_STATUS_DESC", DbType="VarChar(25)")]
		public string EMP_STATUS_DESC
		{
			get
			{
				return this._EMP_STATUS_DESC;
			}
			set
			{
				if ((this._EMP_STATUS_DESC != value))
				{
					this._EMP_STATUS_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GENDER_CODE", DbType="VarChar(1)")]
		public string GENDER_CODE
		{
			get
			{
				return this._GENDER_CODE;
			}
			set
			{
				if ((this._GENDER_CODE != value))
				{
					this._GENDER_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GENDER_DESC", DbType="VarChar(7)")]
		public string GENDER_DESC
		{
			get
			{
				return this._GENDER_DESC;
			}
			set
			{
				if ((this._GENDER_DESC != value))
				{
					this._GENDER_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_TYPE", DbType="VarChar(3)")]
		public string EMP_TYPE
		{
			get
			{
				return this._EMP_TYPE;
			}
			set
			{
				if ((this._EMP_TYPE != value))
				{
					this._EMP_TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_TYPE_DESC", DbType="VarChar(50)")]
		public string EMP_TYPE_DESC
		{
			get
			{
				return this._EMP_TYPE_DESC;
			}
			set
			{
				if ((this._EMP_TYPE_DESC != value))
				{
					this._EMP_TYPE_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STAFF_CATEG", DbType="VarChar(3)")]
		public string STAFF_CATEG
		{
			get
			{
				return this._STAFF_CATEG;
			}
			set
			{
				if ((this._STAFF_CATEG != value))
				{
					this._STAFF_CATEG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STAFF_CATEG_DESC", DbType="VarChar(50)")]
		public string STAFF_CATEG_DESC
		{
			get
			{
				return this._STAFF_CATEG_DESC;
			}
			set
			{
				if ((this._STAFF_CATEG_DESC != value))
				{
					this._STAFF_CATEG_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BIRTH_DATE", DbType="VarChar(8)")]
		public string BIRTH_DATE
		{
			get
			{
				return this._BIRTH_DATE;
			}
			set
			{
				if ((this._BIRTH_DATE != value))
				{
					this._BIRTH_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HIRE_DATE", DbType="VarChar(8)")]
		public string HIRE_DATE
		{
			get
			{
				return this._HIRE_DATE;
			}
			set
			{
				if ((this._HIRE_DATE != value))
				{
					this._HIRE_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERVICE_DATE", DbType="VarChar(8)")]
		public string SERVICE_DATE
		{
			get
			{
				return this._SERVICE_DATE;
			}
			set
			{
				if ((this._SERVICE_DATE != value))
				{
					this._SERVICE_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TERMINATION_DATE", DbType="VarChar(8)")]
		public string TERMINATION_DATE
		{
			get
			{
				return this._TERMINATION_DATE;
			}
			set
			{
				if ((this._TERMINATION_DATE != value))
				{
					this._TERMINATION_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS_HIRE", DbType="VarChar(4)")]
		public string STATUS_HIRE
		{
			get
			{
				return this._STATUS_HIRE;
			}
			set
			{
				if ((this._STATUS_HIRE != value))
				{
					this._STATUS_HIRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS_HIRE_DESC", DbType="VarChar(50)")]
		public string STATUS_HIRE_DESC
		{
			get
			{
				return this._STATUS_HIRE_DESC;
			}
			set
			{
				if ((this._STATUS_HIRE_DESC != value))
				{
					this._STATUS_HIRE_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POINT_OF_HIRE", DbType="VarChar(4)")]
		public string POINT_OF_HIRE
		{
			get
			{
				return this._POINT_OF_HIRE;
			}
			set
			{
				if ((this._POINT_OF_HIRE != value))
				{
					this._POINT_OF_HIRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POINT_OF_HIRE_DESC", DbType="VarChar(50)")]
		public string POINT_OF_HIRE_DESC
		{
			get
			{
				return this._POINT_OF_HIRE_DESC;
			}
			set
			{
				if ((this._POINT_OF_HIRE_DESC != value))
				{
					this._POINT_OF_HIRE_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACCOUNT_DOMAIN", DbType="VarChar(11)")]
		public string ACCOUNT_DOMAIN
		{
			get
			{
				return this._ACCOUNT_DOMAIN;
			}
			set
			{
				if ((this._ACCOUNT_DOMAIN != value))
				{
					this._ACCOUNT_DOMAIN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NRP", DbType="VarChar(50)")]
		public string NRP
		{
			get
			{
				return this._NRP;
			}
			set
			{
				if ((this._NRP != value))
				{
					this._NRP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AGE", DbType="Int")]
		public System.Nullable<int> AGE
		{
			get
			{
				return this._AGE;
			}
			set
			{
				if ((this._AGE != value))
				{
					this._AGE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BLOOD_TYPE", DbType="VarChar(2)")]
		public string BLOOD_TYPE
		{
			get
			{
				return this._BLOOD_TYPE;
			}
			set
			{
				if ((this._BLOOD_TYPE != value))
				{
					this._BLOOD_TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RELIGION_DESC", DbType="VarChar(30)")]
		public string RELIGION_DESC
		{
			get
			{
				return this._RELIGION_DESC;
			}
			set
			{
				if ((this._RELIGION_DESC != value))
				{
					this._RELIGION_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RES_ADDRESS_1", DbType="VarChar(32)")]
		public string RES_ADDRESS_1
		{
			get
			{
				return this._RES_ADDRESS_1;
			}
			set
			{
				if ((this._RES_ADDRESS_1 != value))
				{
					this._RES_ADDRESS_1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RES_ADDRESS_2", DbType="VarChar(32)")]
		public string RES_ADDRESS_2
		{
			get
			{
				return this._RES_ADDRESS_2;
			}
			set
			{
				if ((this._RES_ADDRESS_2 != value))
				{
					this._RES_ADDRESS_2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RES_ADDRESS_3", DbType="VarChar(32)")]
		public string RES_ADDRESS_3
		{
			get
			{
				return this._RES_ADDRESS_3;
			}
			set
			{
				if ((this._RES_ADDRESS_3 != value))
				{
					this._RES_ADDRESS_3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RES_ZIPCODE", DbType="VarChar(10)")]
		public string RES_ZIPCODE
		{
			get
			{
				return this._RES_ZIPCODE;
			}
			set
			{
				if ((this._RES_ZIPCODE != value))
				{
					this._RES_ZIPCODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUPERIOR_ID", DbType="VarChar(10)")]
		public string SUPERIOR_ID
		{
			get
			{
				return this._SUPERIOR_ID;
			}
			set
			{
				if ((this._SUPERIOR_ID != value))
				{
					this._SUPERIOR_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSITION_START_DATE", DbType="VarChar(8)")]
		public string POSITION_START_DATE
		{
			get
			{
				return this._POSITION_START_DATE;
			}
			set
			{
				if ((this._POSITION_START_DATE != value))
				{
					this._POSITION_START_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GOLONGAN", DbType="VarChar(2)")]
		public string GOLONGAN
		{
			get
			{
				return this._GOLONGAN;
			}
			set
			{
				if ((this._GOLONGAN != value))
				{
					this._GOLONGAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GOL_COMPTCY_LEVEL", DbType="VarChar(2)")]
		public string GOL_COMPTCY_LEVEL
		{
			get
			{
				return this._GOL_COMPTCY_LEVEL;
			}
			set
			{
				if ((this._GOL_COMPTCY_LEVEL != value))
				{
					this._GOL_COMPTCY_LEVEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GOL_START_DATE", DbType="VarChar(8)")]
		public string GOL_START_DATE
		{
			get
			{
				return this._GOL_START_DATE;
			}
			set
			{
				if ((this._GOL_START_DATE != value))
				{
					this._GOL_START_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOME_PHONE_NO", DbType="VarChar(16)")]
		public string HOME_PHONE_NO
		{
			get
			{
				return this._HOME_PHONE_NO;
			}
			set
			{
				if ((this._HOME_PHONE_NO != value))
				{
					this._HOME_PHONE_NO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOME_MOBILE_NO", DbType="VarChar(16)")]
		public string HOME_MOBILE_NO
		{
			get
			{
				return this._HOME_MOBILE_NO;
			}
			set
			{
				if ((this._HOME_MOBILE_NO != value))
				{
					this._HOME_MOBILE_NO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RANKS", DbType="VarChar(5)")]
		public string RANKS
		{
			get
			{
				return this._RANKS;
			}
			set
			{
				if ((this._RANKS != value))
				{
					this._RANKS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RANK_DESC", DbType="VarChar(50)")]
		public string RANK_DESC
		{
			get
			{
				return this._RANK_DESC;
			}
			set
			{
				if ((this._RANK_DESC != value))
				{
					this._RANK_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RANK_START_DATE", DbType="VarChar(8)")]
		public string RANK_START_DATE
		{
			get
			{
				return this._RANK_START_DATE;
			}
			set
			{
				if ((this._RANK_START_DATE != value))
				{
					this._RANK_START_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_CODE", DbType="VarChar(250)")]
		public string DEPT_CODE
		{
			get
			{
				return this._DEPT_CODE;
			}
			set
			{
				if ((this._DEPT_CODE != value))
				{
					this._DEPT_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_DESC", DbType="VarChar(50)")]
		public string DEPT_DESC
		{
			get
			{
				return this._DEPT_DESC;
			}
			set
			{
				if ((this._DEPT_DESC != value))
				{
					this._DEPT_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_CODE_DESC", DbType="VarChar(50)")]
		public string DEPT_CODE_DESC
		{
			get
			{
				return this._DEPT_CODE_DESC;
			}
			set
			{
				if ((this._DEPT_CODE_DESC != value))
				{
					this._DEPT_CODE_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIV_CODE", DbType="VarChar(4)")]
		public string DIV_CODE
		{
			get
			{
				return this._DIV_CODE;
			}
			set
			{
				if ((this._DIV_CODE != value))
				{
					this._DIV_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIV_DESC", DbType="VarChar(50)")]
		public string DIV_DESC
		{
			get
			{
				return this._DIV_DESC;
			}
			set
			{
				if ((this._DIV_DESC != value))
				{
					this._DIV_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIV_CODE_DESC", DbType="VarChar(50)")]
		public string DIV_CODE_DESC
		{
			get
			{
				return this._DIV_CODE_DESC;
			}
			set
			{
				if ((this._DIV_CODE_DESC != value))
				{
					this._DIV_CODE_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address_LotusNotes", DbType="NVarChar(255)")]
		public string Address_LotusNotes
		{
			get
			{
				return this._Address_LotusNotes;
			}
			set
			{
				if ((this._Address_LotusNotes != value))
				{
					this._Address_LotusNotes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email_Internet", DbType="NVarChar(255)")]
		public string Email_Internet
		{
			get
			{
				return this._Email_Internet;
			}
			set
			{
				if ((this._Email_Internet != value))
				{
					this._Email_Internet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACTIVE_STATUS", DbType="Int")]
		public System.Nullable<int> ACTIVE_STATUS
		{
			get
			{
				return this._ACTIVE_STATUS;
			}
			set
			{
				if ((this._ACTIVE_STATUS != value))
				{
					this._ACTIVE_STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GENDER", DbType="VarChar(1)")]
		public string GENDER
		{
			get
			{
				return this._GENDER;
			}
			set
			{
				if ((this._GENDER != value))
				{
					this._GENDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME_INITCAP", DbType="VarChar(43)")]
		public string NAME_INITCAP
		{
			get
			{
				return this._NAME_INITCAP;
			}
			set
			{
				if ((this._NAME_INITCAP != value))
				{
					this._NAME_INITCAP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RELIGION", DbType="VarChar(30)")]
		public string RELIGION
		{
			get
			{
				return this._RELIGION;
			}
			set
			{
				if ((this._RELIGION != value))
				{
					this._RELIGION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODIFIED_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> MODIFIED_DATE
		{
			get
			{
				return this._MODIFIED_DATE;
			}
			set
			{
				if ((this._MODIFIED_DATE != value))
				{
					this._MODIFIED_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RANKS_DESC", DbType="VarChar(50)")]
		public string RANKS_DESC
		{
			get
			{
				return this._RANKS_DESC;
			}
			set
			{
				if ((this._RANKS_DESC != value))
				{
					this._RANKS_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RANKS_START_DATE", DbType="VarChar(8)")]
		public string RANKS_START_DATE
		{
			get
			{
				return this._RANKS_START_DATE;
			}
			set
			{
				if ((this._RANKS_START_DATE != value))
				{
					this._RANKS_START_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SECONDARY_POSITION_ID", DbType="VarChar(10)")]
		public string SECONDARY_POSITION_ID
		{
			get
			{
				return this._SECONDARY_POSITION_ID;
			}
			set
			{
				if ((this._SECONDARY_POSITION_ID != value))
				{
					this._SECONDARY_POSITION_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_EDUCATION", DbType="VarChar(5)")]
		public string LAST_EDUCATION
		{
			get
			{
				return this._LAST_EDUCATION;
			}
			set
			{
				if ((this._LAST_EDUCATION != value))
				{
					this._LAST_EDUCATION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BIRTH_PLACE", DbType="VarChar(4)")]
		public string BIRTH_PLACE
		{
			get
			{
				return this._BIRTH_PLACE;
			}
			set
			{
				if ((this._BIRTH_PLACE != value))
				{
					this._BIRTH_PLACE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BIRTH_PLACE_DESC", DbType="VarChar(50)")]
		public string BIRTH_PLACE_DESC
		{
			get
			{
				return this._BIRTH_PLACE_DESC;
			}
			set
			{
				if ((this._BIRTH_PLACE_DESC != value))
				{
					this._BIRTH_PLACE_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GROUP_GOLONGAN", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string GROUP_GOLONGAN
		{
			get
			{
				return this._GROUP_GOLONGAN;
			}
			set
			{
				if ((this._GROUP_GOLONGAN != value))
				{
					this._GROUP_GOLONGAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS_EMP", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string STATUS_EMP
		{
			get
			{
				return this._STATUS_EMP;
			}
			set
			{
				if ((this._STATUS_EMP != value))
				{
					this._STATUS_EMP = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_menuCrossGPID")]
	public partial class vw_menuCrossGPID
	{
		
		private long _Primer;
		
		private int _Id;
		
		private string _Menu;
		
		private System.Nullable<int> _Menu_link;
		
		private string _Link;
		
		private System.Nullable<int> _Urutan;
		
		private string _Deskripsi;
		
		private long _GP_ID;
		
		private System.Nullable<bool> _IsCheck;
		
		private System.Nullable<bool> _A;
		
		private System.Nullable<bool> _D;
		
		private System.Nullable<bool> _E;
		
		private System.Nullable<bool> _R;
		
		public vw_menuCrossGPID()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Primer", DbType="BigInt NOT NULL")]
		public long Primer
		{
			get
			{
				return this._Primer;
			}
			set
			{
				if ((this._Primer != value))
				{
					this._Primer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Menu", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Menu
		{
			get
			{
				return this._Menu;
			}
			set
			{
				if ((this._Menu != value))
				{
					this._Menu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Menu_link", DbType="Int")]
		public System.Nullable<int> Menu_link
		{
			get
			{
				return this._Menu_link;
			}
			set
			{
				if ((this._Menu_link != value))
				{
					this._Menu_link = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Link", DbType="NVarChar(1000)")]
		public string Link
		{
			get
			{
				return this._Link;
			}
			set
			{
				if ((this._Link != value))
				{
					this._Link = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Urutan", DbType="Int")]
		public System.Nullable<int> Urutan
		{
			get
			{
				return this._Urutan;
			}
			set
			{
				if ((this._Urutan != value))
				{
					this._Urutan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deskripsi", DbType="VarChar(50)")]
		public string Deskripsi
		{
			get
			{
				return this._Deskripsi;
			}
			set
			{
				if ((this._Deskripsi != value))
				{
					this._Deskripsi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GP_ID", DbType="BigInt NOT NULL")]
		public long GP_ID
		{
			get
			{
				return this._GP_ID;
			}
			set
			{
				if ((this._GP_ID != value))
				{
					this._GP_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsCheck", DbType="Bit")]
		public System.Nullable<bool> IsCheck
		{
			get
			{
				return this._IsCheck;
			}
			set
			{
				if ((this._IsCheck != value))
				{
					this._IsCheck = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A", DbType="Bit")]
		public System.Nullable<bool> A
		{
			get
			{
				return this._A;
			}
			set
			{
				if ((this._A != value))
				{
					this._A = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D", DbType="Bit")]
		public System.Nullable<bool> D
		{
			get
			{
				return this._D;
			}
			set
			{
				if ((this._D != value))
				{
					this._D = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E", DbType="Bit")]
		public System.Nullable<bool> E
		{
			get
			{
				return this._E;
			}
			set
			{
				if ((this._E != value))
				{
					this._E = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R", DbType="Bit")]
		public System.Nullable<bool> R
		{
			get
			{
				return this._R;
			}
			set
			{
				if ((this._R != value))
				{
					this._R = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Apps.vw_gpId")]
	public partial class vw_gpId
	{
		
		private long _GP;
		
		private string _NRP;
		
		private string _POSITION_ID;
		
		private string _DEPT_CODE;
		
		private string _Deskripsi;
		
		private string _Deskripsi_ID;
		
		private int _ID;
		
		private string _DISTRIK;
		
		private string _NAMA;
		
		private string _DIV_CODE;
		
		public vw_gpId()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GP", DbType="BigInt NOT NULL")]
		public long GP
		{
			get
			{
				return this._GP;
			}
			set
			{
				if ((this._GP != value))
				{
					this._GP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NRP", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NRP
		{
			get
			{
				return this._NRP;
			}
			set
			{
				if ((this._NRP != value))
				{
					this._NRP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSITION_ID", DbType="VarChar(10)")]
		public string POSITION_ID
		{
			get
			{
				return this._POSITION_ID;
			}
			set
			{
				if ((this._POSITION_ID != value))
				{
					this._POSITION_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_CODE", DbType="VarChar(250)")]
		public string DEPT_CODE
		{
			get
			{
				return this._DEPT_CODE;
			}
			set
			{
				if ((this._DEPT_CODE != value))
				{
					this._DEPT_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deskripsi", DbType="VarChar(151)")]
		public string Deskripsi
		{
			get
			{
				return this._Deskripsi;
			}
			set
			{
				if ((this._Deskripsi != value))
				{
					this._Deskripsi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deskripsi_ID", DbType="VarChar(50)")]
		public string Deskripsi_ID
		{
			get
			{
				return this._Deskripsi_ID;
			}
			set
			{
				if ((this._Deskripsi_ID != value))
				{
					this._Deskripsi_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISTRIK", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string DISTRIK
		{
			get
			{
				return this._DISTRIK;
			}
			set
			{
				if ((this._DISTRIK != value))
				{
					this._DISTRIK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAMA", DbType="VarChar(250)")]
		public string NAMA
		{
			get
			{
				return this._NAMA;
			}
			set
			{
				if ((this._NAMA != value))
				{
					this._NAMA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIV_CODE", DbType="VarChar(4)")]
		public string DIV_CODE
		{
			get
			{
				return this._DIV_CODE;
			}
			set
			{
				if ((this._DIV_CODE != value))
				{
					this._DIV_CODE = value;
				}
			}
		}
	}
	
	public partial class cusp_getMenuPermissionsResult
	{
		
		private string _Permission;
		
		private System.Nullable<bool> _A;
		
		private System.Nullable<bool> _D;
		
		private System.Nullable<bool> _E;
		
		private System.Nullable<bool> _R;
		
		public cusp_getMenuPermissionsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Permission", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Permission
		{
			get
			{
				return this._Permission;
			}
			set
			{
				if ((this._Permission != value))
				{
					this._Permission = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A", DbType="Bit")]
		public System.Nullable<bool> A
		{
			get
			{
				return this._A;
			}
			set
			{
				if ((this._A != value))
				{
					this._A = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D", DbType="Bit")]
		public System.Nullable<bool> D
		{
			get
			{
				return this._D;
			}
			set
			{
				if ((this._D != value))
				{
					this._D = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E", DbType="Bit")]
		public System.Nullable<bool> E
		{
			get
			{
				return this._E;
			}
			set
			{
				if ((this._E != value))
				{
					this._E = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R", DbType="Bit")]
		public System.Nullable<bool> R
		{
			get
			{
				return this._R;
			}
			set
			{
				if ((this._R != value))
				{
					this._R = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
