#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrinterMonitoring.Models
{
    using System.Data.Linq;
    using System.Data.Linq.Mapping;
    using System.Data;
    using System.Collections.Generic;
    using System.Reflection;
    using System.Linq;
    using System.Linq.Expressions;
    using System.ComponentModel;
    using System;

    [global::System.Data.Linq.Mapping.DatabaseAttribute(Name = "DB_ALICE")]
    public partial class InventoryDataContext : System.Data.Linq.DataContext
    {

        private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();

        #region Extensibility Method Definitions
        partial void OnCreated();
        #endregion

        public InventoryDataContext() :
                base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DB_ALICEConnectionString1"].ConnectionString, mappingSource)
        {
            OnCreated();
        }

        public InventoryDataContext(System.Data.IDbConnection connection) :
                base(connection, mappingSource)
        {
            OnCreated();
        }

        public InventoryDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) :
                base(connection, mappingSource)
        {
            OnCreated();
        }

        public InventoryDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) :
                base(connection, mappingSource)
        {
            OnCreated();
        }

        //-------------------------------------- Tables

        public System.Data.Linq.Table<inv_master_product> inv_master_products
        {
            get
            {
                return this.GetTable<inv_master_product>();
            }
        }

        public System.Data.Linq.Table<inv_master_in_out> inv_master_in_outs
        {
            get
            {
                return this.GetTable<inv_master_in_out>();
            }
        }

        public System.Data.Linq.Table<inv_master_stock> inv_master_stocks
        {
            get
            {
                return this.GetTable<inv_master_stock>();
            }
        }

        public System.Data.Linq.Table<inv_master_stock_by_po> inv_master_stock_by_pos
        {
            get
            {
                return this.GetTable<inv_master_stock_by_po>();
            }
        }
        
 
    }

    //------------------------------------------ Table Class

    [global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.inv_master_product")]
    public partial class inv_master_product
    {
        private string _id_product;
        private string _desc;
        private string _no_asset;
        private string _type;
        private string _jenis;
        private float _unit_koli;
        private float _unit_each;
        private string _unit_default;
        private string _section;
        private string _expired;
        private System.Nullable<System.DateTime> _last_update;
        private string _insert_by;

        public inv_master_product()
        {
        }

        //[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_id", AutoSync = AutoSync.OnInsert, DbType = "Int NOT NULL IDENTITY", IsPrimaryKey = true, IsDbGenerated = true)]

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_id_product", DbType = "VarChar(10)", IsPrimaryKey = true)]
        public string id_product
        {
            get
            {
                return this._id_product;
            }
            set
            {
                if ((this._id_product != value))
                {
                    this._id_product = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_last_update", DbType = "DateTime")]
        public System.Nullable<System.DateTime> last_update
        {
            get
            {
                return this._last_update;
            }
            set
            {
                if ((this._last_update != value))
                {
                    this._last_update = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_insert_by", DbType = "VarChar(50)")]
        public string insert_by
        {
            get
            {
                return this._insert_by;
            }
            set
            {
                if ((this._insert_by != value))
                {
                    this._insert_by = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_expired", DbType = "VarChar(10)")]
        public string expired
        {
            get
            {
                return this._expired;
            }
            set
            {
                if ((this._expired != value))
                {
                    this._expired = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_section", DbType = "VarChar(50)")]
        public string section
        {
            get
            {
                return this._section;
            }
            set
            {
                if ((this._section != value))
                {
                    this._section = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_unit_each", DbType = "Decimal(10,1)")]
        public float unit_each
        {
            get
            {
                return this._unit_each;
            }
            set
            {
                if ((this._unit_each != value))
                {
                    this._unit_each = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_unit_koli", DbType = "Decimal(10,1)")]
        public float unit_koli
        {
            get
            {
                return this._unit_koli;
            }
            set
            {
                if ((this._unit_koli != value))
                {
                    this._unit_koli = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_unit_default", DbType = "VarChar(10)")]
        public string unit_default
        {
            get
            {
                return this._unit_default;
            }
            set
            {
                if ((this._unit_default != value))
                {
                    this._unit_default = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_jenis", DbType = "VarChar(10)")]
        public string jenis
        {
            get
            {
                return this._jenis;
            }
            set
            {
                if ((this._jenis != value))
                {
                    this._jenis = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_type", DbType = "VarChar(50)")]
        public string type
        {
            get
            {
                return this._type;
            }
            set
            {
                if ((this._type != value))
                {
                    this._type = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_no_asset", DbType = "VarChar(50)")]
        public string no_asset
        {
            get
            {
                return this._no_asset;
            }
            set
            {
                if ((this._no_asset != value))
                {
                    this._no_asset = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_desc", DbType = "VarChar(255)")]
        public string desc
        {
            get
            {
                return this._desc;
            }
            set
            {
                if ((this._desc != value))
                {
                    this._desc = value;
                }
            }
        }
    }


    [global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.inv_master_in_out")]
    public partial class inv_master_in_out
    {
        private int _id;
        private string _id_product;
        private string _desc;
        private string _no_po;
        private float _qty_each;
        private float _qty_koli;
        private string _unit;
        private string _in_out;
        private string _site;
        private bool _status_receipt;
        private string _vendor;
        private string _officer;
        private string _insert_by;
        private System.Nullable<System.DateTime> _last_update;

        public inv_master_in_out()
        {
        }

        //[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_id", AutoSync = AutoSync.OnInsert, DbType = "Int NOT NULL IDENTITY", IsPrimaryKey = true, IsDbGenerated = true)]

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_id", AutoSync = AutoSync.OnInsert, DbType = "Int NOT NULL IDENTITY", IsPrimaryKey = true, IsDbGenerated = true)]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                if ((this._id != value))
                {
                    this._id = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_insert_by", DbType = "VarChar(50)")]
        public string insert_by
        {
            get
            {
                return this._insert_by;
            }
            set
            {
                if ((this._insert_by != value))
                {
                    this._insert_by = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_officer", DbType = "VarChar(50)")]
        public string officer
        {
            get
            {
                return this._officer;
            }
            set
            {
                if ((this._officer != value))
                {
                    this._officer = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_vendor", DbType = "VarChar(50)")]
        public string vendor
        {
            get
            {
                return this._vendor;
            }
            set
            {
                if ((this._vendor != value))
                {
                    this._vendor = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_status_receipt", DbType = "Bit")]
        public bool status_receipt
        {
            get
            {
                return this._status_receipt;
            }
            set
            {
                if ((this._status_receipt != value))
                {
                    this._status_receipt = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_site", DbType = "VarChar(50)")]
        public string site
        {
            get
            {
                return this._site;
            }
            set
            {
                if ((this._site != value))
                {
                    this._site = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_in_out", DbType = "VarChar(10)")]
        public string in_out
        {
            get
            {
                return this._in_out;
            }
            set
            {
                if ((this._in_out != value))
                {
                    this._in_out = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_qty_each", DbType = "Decimal(10,1)")]
        public float qty_each
        {
            get
            {
                return this._qty_each;
            }
            set
            {
                if ((this._qty_each != value))
                {
                    this._qty_each = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_qty_koli", DbType = "Decimal(10,1)")]
        public float qty_koli
        {
            get
            {
                return this._qty_koli;
            }
            set
            {
                if ((this._qty_koli != value))
                {
                    this._qty_koli = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_unit", DbType = "VarChar(10)")]
        public string unit
        {
            get
            {
                return this._unit;
            }
            set
            {
                if ((this._unit != value))
                {
                    this._unit = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_no_po", DbType = "VarChar(50)")]
        public string no_po
        {
            get
            {
                return this._no_po;
            }
            set
            {
                if ((this._no_po != value))
                {
                    this._no_po = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_desc", DbType = "VarChar(255)")]
        public string desc
        {
            get
            {
                return this._desc;
            }
            set
            {
                if ((this._desc != value))
                {
                    this._desc = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_id_product", DbType = "VarChar(10)")]
        public string id_product
        {
            get
            {
                return this._id_product;
            }
            set
            {
                if ((this._id_product != value))
                {
                    this._id_product = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_last_update", DbType = "DateTime")]
        public System.Nullable<System.DateTime> last_update
        {
            get
            {
                return this._last_update;
            }
            set
            {
                if ((this._last_update != value))
                {
                    this._last_update = value;
                }
            }
        }
    }

    [global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.inv_master_stock")]
    public partial class inv_master_stock
    {
        private string _id_product;
        private string _desc;
        private string _type;
        private string _jenis;
        private string _section;
        private string _unit_default;
        private float _stock_each;
        private float _stock_koli;
        private System.Nullable<System.DateTime> _last_transaction;
        private string _expired;

        public inv_master_stock()
        {
        }

        //[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_id", AutoSync = AutoSync.OnInsert, DbType = "Int NOT NULL IDENTITY", IsPrimaryKey = true, IsDbGenerated = true)]

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_id_product", DbType = "VarChar(10)", IsPrimaryKey = true)]
        public string id_product
        {
            get
            {
                return this._id_product;
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_last_transaction", DbType = "DateTime")]
        public System.Nullable<System.DateTime> last_transaction
        {
            get
            {
                return this._last_transaction;
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_expired", DbType = "VarChar(10)")]
        public string expired
        {
            get
            {
                return this._expired;
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_section", DbType = "VarChar(50)")]
        public string section
        {
            get
            {
                return this._section;
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_stock_each", DbType = "Decimal(10,1)")]
        public float stock_each
        {
            get
            {
                return this._stock_each;
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_stock_koli", DbType = "Decimal(10,1)")]
        public float stock_koli
        {
            get
            {
                return this._stock_koli;
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_unit_default", DbType = "VarChar(10)")]
        public string unit_default
        {
            get
            {
                return this._unit_default;
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_jenis", DbType = "VarChar(10)")]
        public string jenis
        {
            get
            {
                return this._jenis;
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_type", DbType = "VarChar(50)")]
        public string type
        {
            get
            {
                return this._type;
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_desc", DbType = "VarChar(255)")]
        public string desc
        {
            get
            {
                return this._desc;
            }
        }
    }


    [global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.inv_master_stock_by_po")]
    public partial class inv_master_stock_by_po
    {
        private string _id_product;
        private string _desc;
        private string _no_po;
        private string _type;
        private string _jenis;
        private string _section;
        private string _unit_default;
        private float _stock_each;
        private float _stock_koli;
        private System.Nullable<System.DateTime> _last_transaction;
        private string _expired;

        public inv_master_stock_by_po()
        {
        }

        //[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_id", AutoSync = AutoSync.OnInsert, DbType = "Int NOT NULL IDENTITY", IsPrimaryKey = true, IsDbGenerated = true)]

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_id_product", DbType = "VarChar(10)")]
        public string id_product
        {
            get
            {
                return this._id_product;
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_last_transaction", DbType = "DateTime")]
        public System.Nullable<System.DateTime> last_transaction
        {
            get
            {
                return this._last_transaction;
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_expired", DbType = "VarChar(10)")]
        public string expired
        {
            get
            {
                return this._expired;
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_section", DbType = "VarChar(50)")]
        public string section
        {
            get
            {
                return this._section;
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_stock_each", DbType = "Decimal(10,1)")]
        public float stock_each
        {
            get
            {
                return this._stock_each;
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_stock_koli", DbType = "Decimal(10,1)")]
        public float stock_koli
        {
            get
            {
                return this._stock_koli;
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_unit_default", DbType = "VarChar(10)")]
        public string unit_default
        {
            get
            {
                return this._unit_default;
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_jenis", DbType = "VarChar(10)")]
        public string jenis
        {
            get
            {
                return this._jenis;
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_type", DbType = "VarChar(50)")]
        public string type
        {
            get
            {
                return this._type;
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_no_po", DbType = "VarChar(50)")]
        public string no_po
        {
            get
            {
                return this._no_po;
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_desc", DbType = "VarChar(255)")]
        public string desc
        {
            get
            {
                return this._desc;
            }
        }
    }









}
#pragma warning restore 1591
