#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrinterMonitoring.Models
{
    using System.Data.Linq;
    using System.Data.Linq.Mapping;
    using System.Data;
    using System.Collections.Generic;
    using System.Reflection;
    using System.Linq;
    using System.Linq.Expressions;
    using System.ComponentModel;
    using System;

    [global::System.Data.Linq.Mapping.DatabaseAttribute(Name = "DB_ALICE")]
    public partial class LicenseDataContext : System.Data.Linq.DataContext
    {

        private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();

        #region Extensibility Method Definitions
        partial void OnCreated();
        #endregion

        public LicenseDataContext() :
                base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DB_ALICEConnectionString1"].ConnectionString, mappingSource)
        {
            OnCreated();
        }

        public LicenseDataContext(System.Data.IDbConnection connection) :
                base(connection, mappingSource)
        {
            OnCreated();
        }

        public LicenseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) :
                base(connection, mappingSource)
        {
            OnCreated();
        }

        public LicenseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) :
                base(connection, mappingSource)
        {
            OnCreated();
        }

        //-------------------------------------- Tables

        public System.Data.Linq.Table<VW_PR_PO_ELLIPSE_REVIEW> VW_PR_PO_ELLIPSE_REVIEWs
        {
            get
            {
                return this.GetTable<VW_PR_PO_ELLIPSE_REVIEW>();
            }
        }

        public System.Data.Linq.Table<TBL_LICENSE_REGISTER> TBL_LICENSE_REGISTERs
        {
            get
            {
                return this.GetTable<TBL_LICENSE_REGISTER>();
            }
        }

        public System.Data.Linq.Table<TBL_LICENSE_RENEWAL> TBL_LICENSE_RENEWALs
        {
            get
            {
                return this.GetTable<TBL_LICENSE_RENEWAL>();
            }
        }

        public System.Data.Linq.Table<TBL_T_ASSET_PERFORMANCE_MASTER> TBL_T_ASSET_PERFORMANCE_MASTERs
        {
            get
            {
                return this.GetTable<TBL_T_ASSET_PERFORMANCE_MASTER>();
            }
        }

        public System.Data.Linq.Table<TblLicenseDetail> TblLicenseDetails
        {
            get
            {
                return this.GetTable<TblLicenseDetail>();
            }
        }

        public System.Data.Linq.Table<TBL_LIST_DISTRICT> TBL_LIST_DISTRICTs
        {
            get
            {
                return this.GetTable<TBL_LIST_DISTRICT>();
            }
        }

        public System.Data.Linq.Table<VW_TblLicenseDetail> VW_TblLicenseDetails
        {
            get
            {
                return this.GetTable<VW_TblLicenseDetail>();
            }
        }

        public System.Data.Linq.Table<VW_EMPLOYEE_PAMA> VW_EMPLOYEE_PAMAs
        {
            get
            {
                return this.GetTable<VW_EMPLOYEE_PAMA>();
            }
        }

        public System.Data.Linq.Table<TemplateProduct> TemplateProducts
        {
            get
            {
                return this.GetTable<TemplateProduct>();
            }
        }
        


    }

    //------------------------------------------ Table Class

    


    [global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.TemplateProduct")]
    public partial class TemplateProduct
    {
        private int _id;
        private string _ProductID;
        private string _Name;
        private string _GroupID;
        private string _IsUsed;
        private string _Description;
        private string _UserID;
        private string _LastAccessedDate;
        private string _GroupProduct;
        private string _Major;
        private string _Minor;

        public TemplateProduct()
        {
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Minor", DbType = "VarChar(50)")]
        public string Minor
        {
            get
            {
                return this._Minor;
            }
            set
            {
                if ((this._Minor != value))
                {
                    this._Minor = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Major", DbType = "VarChar(50)")]
        public string Major
        {
            get
            {
                return this._Major;
            }
            set
            {
                if ((this._Major != value))
                {
                    this._Major = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_GroupProduct", DbType = "VarChar(50)")]
        public string GroupProduct
        {
            get
            {
                return this._GroupProduct;
            }
            set
            {
                if ((this._GroupProduct != value))
                {
                    this._GroupProduct = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_LastAccessedDate", DbType = "DateTime")]
        public string LastAccessedDate
        {
            get
            {
                return this._LastAccessedDate;
            }
            set
            {
                if ((this._LastAccessedDate != value))
                {
                    this._LastAccessedDate = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_UserID", DbType = "VarChar(50)")]
        public string UserID
        {
            get
            {
                return this._UserID;
            }
            set
            {
                if ((this._UserID != value))
                {
                    this._UserID = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Description", DbType = "VarChar(50)")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                if ((this._Description != value))
                {
                    this._Description = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_IsUsed", DbType = "Int")]
        public string IsUsed
        {
            get
            {
                return this._IsUsed;
            }
            set
            {
                if ((this._IsUsed != value))
                {
                    this._IsUsed = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_GroupID", DbType = "VarChar(50)")]
        public string GroupID
        {
            get
            {
                return this._GroupID;
            }
            set
            {
                if ((this._GroupID != value))
                {
                    this._GroupID = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Name", DbType = "VarChar(50)")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                if ((this._Name != value))
                {
                    this._Name = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ProductID", DbType = "VarChar(50)")]
        public string ProductID
        {
            get
            {
                return this._ProductID;
            }
            set
            {
                if ((this._ProductID != value))
                {
                    this._ProductID = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_id", AutoSync = AutoSync.OnInsert, DbType = "Int NOT NULL IDENTITY", IsPrimaryKey = true, IsDbGenerated = true)]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                if ((this._id != value))
                {
                    this._id = value;
                }
            }
        }

    }

    [global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.VW_EMPLOYEE_PAMA")]
    public partial class VW_EMPLOYEE_PAMA
    {
        private int _id;
        private string _NRP;
        private string _FIRST_NAME;
        private string _SURNAME;
        private string _NAME;
        private string _GENDER_CODE;
        private string _AGE;
        private string _HOME_PHONE_NO;
        private string _DIV_CODE;
        private string _COMPUTER_NAME;

        public VW_EMPLOYEE_PAMA()
        {
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_DIV_CODE", DbType = "VarChar(50)")]
        public string COMPUTER_NAME
        {
            get
            {
                return this._COMPUTER_NAME;
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_DIV_CODE", DbType = "VarChar(50)")]
        public string DIV_CODE
        {
            get
            {
                return this._DIV_CODE;
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_HOME_PHONE_NO", DbType = "VarChar(50)")]
        public string HOME_PHONE_NO
        {
            get
            {
                return this._HOME_PHONE_NO;
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_AGE", DbType = "VarChar(50)")]
        public string AGE
        {
            get
            {
                return this._AGE;
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_GENDER_CODE", DbType = "VarChar(50)")]
        public string GENDER_CODE
        {
            get
            {
                return this._GENDER_CODE;
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_NAME", DbType = "VarChar(50)")]
        public string NAME
        {
            get
            {
                return this._NAME;
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_SURNAME", DbType = "VarChar(50)")]
        public string SURNAME
        {
            get
            {
                return this._SURNAME;
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_FIRST_NAME", DbType = "VarChar(50)")]
        public string FIRST_NAME
        {
            get
            {
                return this._FIRST_NAME;
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_NRP", DbType = "VarChar(50)")]
        public string NRP
        {
            get
            {
                return this._NRP;
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_id", AutoSync = AutoSync.OnInsert, DbType = "Int NOT NULL IDENTITY", IsPrimaryKey = true, IsDbGenerated = true)]
        public int id
        {
            get
            {
                return this._id;
            }
        }

    }

    [global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.TBL_LIST_DISTRICT")]
    public partial class TBL_LIST_DISTRICT
    {
        private int _id;
        private string _district;

        public TBL_LIST_DISTRICT()
        {
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_district", DbType = "VarChar(50)")]
        public string district
        {
            get
            {
                return this._district;
            }
            set
            {
                if ((this._district != value))
                {
                    this._district = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_id", AutoSync = AutoSync.OnInsert, DbType = "Int NOT NULL IDENTITY", IsPrimaryKey = true, IsDbGenerated = true)]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                if ((this._id != value))
                {
                    this._id = value;
                }
            }
        }

    }

    [global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.TblLicenseDetail")]
    public partial class TblLicenseDetail
    {
        private int _id;
        private string _LicenseNumber;
        private string _LicenseNumberDetail;
        private string _SoftwareName;
        private string _SerialNumber;
        private string _RegistrationNumber;
        private string _Description;
        private string _DistrictID;
        private string _UserID;
        private string _LastAccessedDate;
        private string _Username;
        private string _Nrp;
        private string _DivCode;
        private string _TicketNumber;
        private string _StatusUser;
        private string _ComputerName;

        public TblLicenseDetail()
        {
        }

        

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ComputerName", DbType = "VarChar(50)")]
        public string ComputerName
        {
            get
            {
                return this._ComputerName;
            }
            set
            {
                if ((this._ComputerName != value))
                {
                    this._ComputerName = value;
                }
            }
        }


        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_SoftwareName", DbType = "VarChar(50)")]
        public string SoftwareName
        {
            get
            {
                return this._SoftwareName;
            }
            set
            {
                if ((this._SoftwareName != value))
                {
                    this._SoftwareName = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_StatusUser", DbType = "VarChar(50)")]
        public string StatusUser
        {
            get
            {
                return this._StatusUser;
            }
            set
            {
                if ((this._StatusUser != value))
                {
                    this._StatusUser = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_TicketNumber", DbType = "VarChar(50)")]
        public string TicketNumber
        {
            get
            {
                return this._TicketNumber;
            }
            set
            {
                if ((this._TicketNumber != value))
                {
                    this._TicketNumber = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_DivCode", DbType = "VarChar(50)")]
        public string DivCode
        {
            get
            {
                return this._DivCode;
            }
            set
            {
                if ((this._DivCode != value))
                {
                    this._DivCode = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Nrp", DbType = "VarChar(50)")]
        public string Nrp
        {
            get
            {
                return this._Nrp;
            }
            set
            {
                if ((this._Nrp != value))
                {
                    this._Nrp = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Username", DbType = "VarChar(50)")]
        public string Username
        {
            get
            {
                return this._Username;
            }
            set
            {
                if ((this._Username != value))
                {
                    this._Username = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_LastAccessedDate", DbType = "DateTime")]
        public string LastAccessedDate
        {
            get
            {
                return this._LastAccessedDate;
            }
            set
            {
                if ((this._LastAccessedDate != value))
                {
                    this._LastAccessedDate = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_UserID", DbType = "VarChar(50)")]
        public string UserID
        {
            get
            {
                return this._UserID;
            }
            set
            {
                if ((this._UserID != value))
                {
                    this._UserID = value;
                }
            }
        }

        

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_DistrictID", DbType = "VarChar(50)")]
        public string DistrictID
        {
            get
            {
                return this._DistrictID;
            }
            set
            {
                if ((this._DistrictID != value))
                {
                    this._DistrictID = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Description", DbType = "VarChar(255)")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                if ((this._Description != value))
                {
                    this._Description = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_RegistrationNumber", DbType = "Int")]
        public string RegistrationNumber
        {
            get
            {
                return this._RegistrationNumber;
            }
            set
            {
                if ((this._RegistrationNumber != value))
                {
                    this._RegistrationNumber = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_SerialNumber", DbType = "VarChar(50)")]
        public string SerialNumber
        {
            get
            {
                return this._SerialNumber;
            }
            set
            {
                if ((this._SerialNumber != value))
                {
                    this._SerialNumber = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_LicenseNumberDetail", DbType = "VarChar(50)")]
        public string LicenseNumberDetail
        {
            get
            {
                return this._LicenseNumberDetail;
            }
            set
            {
                if ((this._LicenseNumberDetail != value))
                {
                    this._LicenseNumberDetail = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_LicenseNumber", DbType = "VarChar(50)")]
        public string LicenseNumber
        {
            get
            {
                return this._LicenseNumber;
            }
            set
            {
                if ((this._LicenseNumber != value))
                {
                    this._LicenseNumber = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_id", AutoSync = AutoSync.OnInsert, DbType = "Int NOT NULL IDENTITY", IsPrimaryKey = true, IsDbGenerated = true)]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                if ((this._id != value))
                {
                    this._id = value;
                }
            }
        }
    }

    [global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.VW_TblLicenseDetail")]
    public partial class VW_TblLicenseDetail
    {
        private int _id;
        private string _LicenseNumber;
        private string _LicenseNumberDetail;
        private string _SoftwareName;
        private string _SerialNumber;
        private string _RegistrationNumber;
        private string _Description;
        private string _DistrictID;
        private string _UserID;
        private string _LastAccessedDate;
        private string _Username;
        private string _Nrp;
        private string _DivCode;
        private string _TicketNumber;
        private string _StatusUser;
        private string _LicenseStatus;
        private string _ComputerName;

        public VW_TblLicenseDetail()
        {
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ComputerName", DbType = "VarChar(50)")]
        public string ComputerName
        {
            get
            {
                return this._ComputerName;
            }
            set
            {
                if ((this._ComputerName != value))
                {
                    this._ComputerName = value;
                }
            }
        }


        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_SoftwareName", DbType = "VarChar(50)")]
        public string SoftwareName
        {
            get
            {
                return this._SoftwareName;
            }
            set
            {
                if ((this._SoftwareName != value))
                {
                    this._SoftwareName = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_LicenseStatus", DbType = "VarChar(50)")]
        public string LicenseStatus
        {
            get
            {
                return this._LicenseStatus;
            }
            set
            {
                if ((this._LicenseStatus != value))
                {
                    this._LicenseStatus = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_StatusUser", DbType = "VarChar(50)")]
        public string StatusUser
        {
            get
            {
                return this._StatusUser;
            }
            set
            {
                if ((this._StatusUser != value))
                {
                    this._StatusUser = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_TicketNumber", DbType = "VarChar(50)")]
        public string TicketNumber
        {
            get
            {
                return this._TicketNumber;
            }
            set
            {
                if ((this._TicketNumber != value))
                {
                    this._TicketNumber = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_DivCode", DbType = "VarChar(50)")]
        public string DivCode
        {
            get
            {
                return this._DivCode;
            }
            set
            {
                if ((this._DivCode != value))
                {
                    this._DivCode = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Nrp", DbType = "VarChar(50)")]
        public string Nrp
        {
            get
            {
                return this._Nrp;
            }
            set
            {
                if ((this._Nrp != value))
                {
                    this._Nrp = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Username", DbType = "VarChar(50)")]
        public string Username
        {
            get
            {
                return this._Username;
            }
            set
            {
                if ((this._Username != value))
                {
                    this._Username = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_LastAccessedDate", DbType = "DateTime")]
        public string LastAccessedDate
        {
            get
            {
                return this._LastAccessedDate;
            }
            set
            {
                if ((this._LastAccessedDate != value))
                {
                    this._LastAccessedDate = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_UserID", DbType = "VarChar(50)")]
        public string UserID
        {
            get
            {
                return this._UserID;
            }
            set
            {
                if ((this._UserID != value))
                {
                    this._UserID = value;
                }
            }
        }



        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_DistrictID", DbType = "VarChar(50)")]
        public string DistrictID
        {
            get
            {
                return this._DistrictID;
            }
            set
            {
                if ((this._DistrictID != value))
                {
                    this._DistrictID = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Description", DbType = "VarChar(255)")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                if ((this._Description != value))
                {
                    this._Description = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_RegistrationNumber", DbType = "Int")]
        public string RegistrationNumber
        {
            get
            {
                return this._RegistrationNumber;
            }
            set
            {
                if ((this._RegistrationNumber != value))
                {
                    this._RegistrationNumber = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_SerialNumber", DbType = "VarChar(50)")]
        public string SerialNumber
        {
            get
            {
                return this._SerialNumber;
            }
            set
            {
                if ((this._SerialNumber != value))
                {
                    this._SerialNumber = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_LicenseNumberDetail", DbType = "VarChar(50)")]
        public string LicenseNumberDetail
        {
            get
            {
                return this._LicenseNumberDetail;
            }
            set
            {
                if ((this._LicenseNumberDetail != value))
                {
                    this._LicenseNumberDetail = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_LicenseNumber", DbType = "VarChar(50)")]
        public string LicenseNumber
        {
            get
            {
                return this._LicenseNumber;
            }
            set
            {
                if ((this._LicenseNumber != value))
                {
                    this._LicenseNumber = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_id", AutoSync = AutoSync.OnInsert, DbType = "Int NOT NULL IDENTITY", IsPrimaryKey = true, IsDbGenerated = true)]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                if ((this._id != value))
                {
                    this._id = value;
                }
            }
        }
    }

    [global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.TBL_T_ASSET_PERFORMANCE_MASTER")]
    public partial class TBL_T_ASSET_PERFORMANCE_MASTER
    {
        private string _ASSET_NO;
        private string _DEVICE_NAME;
        private string _DSTRCT_CODE;
        private string _ASSET_DESC;
        private string _PO_NO;
        private string _SERIAL_NO_ELLIPSE;
        private string _SERIAL_NO_LANSWEEPER;
        private string _IPAddress;
        private System.Nullable<System.DateTime> _UPDATE_AT;
        private string _UPDATE_BY;

        public TBL_T_ASSET_PERFORMANCE_MASTER()
        {
        }

        //[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_id", AutoSync = AutoSync.OnInsert, DbType = "Int NOT NULL IDENTITY", IsPrimaryKey = true, IsDbGenerated = true)]
        
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ASSET_NO", DbType = "VarChar(50)", IsPrimaryKey = true)]
        public string ASSET_NO
        {
            get
            {
                return this._ASSET_NO;
            }
            set
            {
                if ((this._ASSET_NO != value))
                {
                    this._ASSET_NO = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_DEVICE_NAME", DbType = "VarChar(50)")]
        public string DEVICE_NAME
        {
            get
            {
                return this._DEVICE_NAME;
            }
            set
            {
                if ((this._DEVICE_NAME != value))
                {
                    this._DEVICE_NAME = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_DSTRCT_CODE", DbType = "VarChar(50)")]
        public string DSTRCT_CODE
        {
            get
            {
                return this._DSTRCT_CODE;
            }
            set
            {
                if ((this._DSTRCT_CODE != value))
                {
                    this._DSTRCT_CODE = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ASSET_DESC", DbType = "VarChar(50)")]
        public string ASSET_DESC
        {
            get
            {
                return this._ASSET_DESC;
            }
            set
            {
                if ((this._ASSET_DESC != value))
                {
                    this._ASSET_DESC = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_PO_NO", DbType = "VarChar(50)")]
        public string PO_NO
        {
            get
            {
                return this._PO_NO;
            }
            set
            {
                if ((this._PO_NO != value))
                {
                    this._PO_NO = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_SERIAL_NO_ELLIPSE", DbType = "VarChar(50)")]
        public string SERIAL_NO_ELLIPSE
        {
            get
            {
                return this._SERIAL_NO_ELLIPSE;
            }
            set
            {
                if ((this._SERIAL_NO_ELLIPSE != value))
                {
                    this._SERIAL_NO_ELLIPSE = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_SERIAL_NO_LANSWEEPER", DbType = "VarChar(50)")]
        public string SERIAL_NO_LANSWEEPER
        {
            get
            {
                return this._SERIAL_NO_LANSWEEPER;
            }
            set
            {
                if ((this._SERIAL_NO_LANSWEEPER != value))
                {
                    this._SERIAL_NO_LANSWEEPER = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_IPAddress", DbType = "VarChar(50)")]
        public string IPAddress
        {
            get
            {
                return this._IPAddress;
            }
            set
            {
                if ((this._IPAddress != value))
                {
                    this._IPAddress = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_UPDATE_AT", DbType = "DateTime")]
        public System.Nullable<System.DateTime> UPDATE_AT
        {
            get
            {
                return this._UPDATE_AT;
            }
            set
            {
                if ((this._UPDATE_AT != value))
                {
                    this._UPDATE_AT = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_UPDATE_BY", DbType = "VarChar(50)")]
        public string UPDATE_BY
        {
            get
            {
                return this._UPDATE_BY;
            }
            set
            {
                if ((this._UPDATE_BY != value))
                {
                    this._UPDATE_BY = value;
                }
            }
        }


        
    }

    [global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.TBL_LICENSE_RENEWAL")]
    public partial class TBL_LICENSE_RENEWAL
    {

        private string _software_id;
        private string _license_number;
        private string _license_type;
        private string _po_number;
        private string _item_number;
        private string _qty;
        private string _vendor_name;
        private string _currency;
        private string _price;
        private string _license_category;
        private string _start;
        private string _end;
        private string _desc;
        private string _timestamps;
        private string _last_update;
        private int _id;

        public TBL_LICENSE_RENEWAL()
        {
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_last_update", DbType = "DateTime")]
        public string last_update
        {
            get
            {
                return this._last_update;
            }
            set
            {
                if ((this._last_update != value))
                {
                    this._last_update = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_timestamps", DbType = "DateTime")]
        public string timestamps
        {
            get
            {
                return this._timestamps;
            }
            set
            {
                if ((this._timestamps != value))
                {
                    this._timestamps = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_desc", DbType = "VarChar(50)")]
        public string desc
        {
            get
            {
                return this._desc;
            }
            set
            {
                if ((this._desc != value))
                {
                    this._desc = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_end", DbType = "Date")]
        public string end
        {
            get
            {
                return this._end;
            }
            set
            {
                if ((this._end != value))
                {
                    this._end = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_start", DbType = "Date")]
        public string start
        {
            get
            {
                return this._start;
            }
            set
            {
                if ((this._start != value))
                {
                    this._start = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_license_category", DbType = "VarChar(50)")]
        public string license_category
        {
            get
            {
                return this._license_category;
            }
            set
            {
                if ((this._license_category != value))
                {
                    this._license_category = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_price", DbType = "VarChar(50)")]
        public string price
        {
            get
            {
                return this._price;
            }
            set
            {
                if ((this._price != value))
                {
                    this._price = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_currency", DbType = "VarChar(50)")]
        public string currency
        {
            get
            {
                return this._currency;
            }
            set
            {
                if ((this._currency != value))
                {
                    this._currency = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_vendor_name", DbType = "VarChar(50)")]
        public string vendor_name
        {
            get
            {
                return this._vendor_name;
            }
            set
            {
                if ((this._vendor_name != value))
                {
                    this._vendor_name = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_qty", DbType = "VarChar(50)")]
        public string qty
        {
            get
            {
                return this._qty;
            }
            set
            {
                if ((this._qty != value))
                {
                    this._qty = value;
                }
            }
        }



        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_item_number", DbType = "VarChar(50)")]
        public string item_number
        {
            get
            {
                return this._item_number;
            }
            set
            {
                if ((this._item_number != value))
                {
                    this._item_number = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_po_number", DbType = "VarChar(50)")]
        public string po_number
        {
            get
            {
                return this._po_number;
            }
            set
            {
                if ((this._po_number != value))
                {
                    this._po_number = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_license_type", DbType = "VarChar(50)")]
        public string license_type
        {
            get
            {
                return this._license_type;
            }
            set
            {
                if ((this._license_type != value))
                {
                    this._license_type = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_software_id", DbType = "VarChar(50)")]
        public string software_id
        {
            get
            {
                return this._software_id;
            }
            set
            {
                if ((this._software_id != value))
                {
                    this._software_id = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_license_number", DbType = "VarChar(50)")]
        public string license_number
        {
            get
            {
                return this._license_number;
            }
            set
            {
                if ((this._license_number != value))
                {
                    this._license_number = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_id", AutoSync = AutoSync.OnInsert, DbType = "Int NOT NULL IDENTITY", IsPrimaryKey = true, IsDbGenerated = true)]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                if ((this._id != value))
                {
                    this._id = value;
                }
            }
        }
    }

    [global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.VW_PR_PO_ELLIPSE_REVIEW")]
    public partial class VW_PR_PO_ELLIPSE_REVIEW
    {

        private string _PO;
        private string _CURR;
        private string _HARGA_PO;
        private int _QTY;
        private string _PO_ITEM;
        private string _SUPPLIER_PO;

        public VW_PR_PO_ELLIPSE_REVIEW()
        {
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_SUPPLIER_PO", DbType = "VarChar(50)")]
        public string SUPPLIER_PO
        {
            get
            {
                return this._SUPPLIER_PO;
            }
            set
            {
                if ((this._SUPPLIER_PO != value))
                {
                    this._SUPPLIER_PO = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_PO_ITEM", DbType = "VarChar(50)")]
        public string PO_ITEM
        {
            get
            {
                return this._PO_ITEM;
            }
            set
            {
                if ((this._PO_ITEM != value))
                {
                    this._PO_ITEM = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_PO", DbType = "VarChar(50)")]
        public string PO
        {
            get
            {
                return this._PO;
            }
            set
            {
                if ((this._PO != value))
                {
                    this._PO = value;
                }
            }
        }


        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_CURR", DbType = "VarChar(50)")]
        public string CURR
        {
            get
            {
                return this._CURR;
            }
            set
            {
                if ((this._CURR != value))
                {
                    this._CURR = value;
                }
            }
        }


        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_HARGA_PO", DbType = "Int")]
        public string HARGA_PO
        {
            get
            {
                return this._HARGA_PO;
            }
            set
            {
                if ((this._HARGA_PO != value))
                {
                    this._HARGA_PO = value;
                }
            }
        }


        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_QTY", DbType = "Decimal(11,2)")]
        public int QTY
        {
            get
            {
                return this._QTY;
            }
            set
            {
                if ((this._QTY != value))
                {
                    this._QTY = value;
                }
            }
        }
    }


    [global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.TBL_LICENSE_REGISTER")]
    public partial class TBL_LICENSE_REGISTER
    {

        private string _software_id;
        private string _software_name;
        private string _license_number;
        private string _license_type;
        private string _po_number;
        private string _item_number;
        private string _qty;
        private string _vendor_name;
        private string _currency;
        private string _price;
        private string _license_category;
        private string _start;
        private string _end;
        private string _desc;
        private string _timestamps;
        private string _last_update;
        private string _file;
        private string _created_by;
        private string _updated_by;
        private string _deleted_at;
        private int _id;

        public TBL_LICENSE_REGISTER()
        {
        }
        
        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_deleted_at", DbType = "DateTime")]
        public string deleted_at
        {
            get
            {
                return this._deleted_at;
            }
            set
            {
                if ((this._deleted_at != value))
                {
                    this._deleted_at = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_last_update", DbType = "DateTime")]
        public string last_update
        {
            get
            {
                return this._last_update;
            }
            set
            {
                if ((this._last_update != value))
                {
                    this._last_update = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_timestamps", DbType = "DateTime")]
        public string timestamps
        {
            get
            {
                return this._timestamps;
            }
            set
            {
                if ((this._timestamps != value))
                {
                    this._timestamps = value;
                }
            }
        }
        

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_created_by", DbType = "VarChar(50)")]
        public string created_by
        {
            get
            {
                return this._created_by;
            }
            set
            {
                if ((this._created_by != value))
                {
                    this._created_by = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_updated_by", DbType = "VarChar(50)")]
        public string updated_by
        {
            get
            {
                return this._updated_by;
            }
            set
            {
                if ((this._updated_by != value))
                {
                    this._updated_by = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_file", DbType = "VarChar(255)")]
        public string file
        {
            get
            {
                return this._file;
            }
            set
            {
                if ((this._file != value))
                {
                    this._file = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_desc", DbType = "VarChar(50)")]
        public string desc
        {
            get
            {
                return this._desc;
            }
            set
            {
                if ((this._desc != value))
                {
                    this._desc = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_end", DbType = "Date")]
        public string end
        {
            get
            {
                return this._end;
            }
            set
            {
                if ((this._end != value))
                {
                    this._end = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_start", DbType = "Date")]
        public string start
        {
            get
            {
                return this._start;
            }
            set
            {
                if ((this._start != value))
                {
                    this._start = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_license_category", DbType = "VarChar(50)")]
        public string license_category
        {
            get
            {
                return this._license_category;
            }
            set
            {
                if ((this._license_category != value))
                {
                    this._license_category = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_price", DbType = "Int")]
        public string price
        {
            get
            {
                return this._price;
            }
            set
            {
                if ((this._price != value))
                {
                    this._price = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_currency", DbType = "VarChar(50)")]
        public string currency
        {
            get
            {
                return this._currency;
            }
            set
            {
                if ((this._currency != value))
                {
                    this._currency = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_vendor_name", DbType = "VarChar(50)")]
        public string vendor_name
        {
            get
            {
                return this._vendor_name;
            }
            set
            {
                if ((this._vendor_name != value))
                {
                    this._vendor_name = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_qty", DbType = "Int")]
        public string qty
        {
            get
            {
                return this._qty;
            }
            set
            {
                if ((this._qty != value))
                {
                    this._qty = value;
                }
            }
        }



        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_item_number", DbType = "VarChar(50)")]
        public string item_number
        {
            get
            {
                return this._item_number;
            }
            set
            {
                if ((this._item_number != value))
                {
                    this._item_number = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_po_number", DbType = "VarChar(50)")]
        public string po_number
        {
            get
            {
                return this._po_number;
            }
            set
            {
                if ((this._po_number != value))
                {
                    this._po_number = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_license_type", DbType = "VarChar(50)")]
        public string license_type
        {
            get
            {
                return this._license_type;
            }
            set
            {
                if ((this._license_type != value))
                {
                    this._license_type = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_software_name", DbType = "VarChar(50)")]
        public string software_name
        {
            get
            {
                return this._software_name;
            }
            set
            {
                if ((this._software_name != value))
                {
                    this._software_name = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_software_id", DbType = "VarChar(50)")]
        public string software_id
        {
            get
            {
                return this._software_id;
            }
            set
            {
                if ((this._software_id != value))
                {
                    this._software_id = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_license_number", DbType = "VarChar(50)")]
        public string license_number
        {
            get
            {
                return this._license_number;
            }
            set
            {
                if ((this._license_number != value))
                {
                    this._license_number = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_id", AutoSync = AutoSync.OnInsert, DbType = "Int NOT NULL IDENTITY", IsPrimaryKey = true, IsDbGenerated = true)]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                if ((this._id != value))
                {
                    this._id = value;
                }
            }
        }

    }










}
#pragma warning restore 1591
